apiVersion: v1
kind: Service
metadata:
  name: fitness-notification-service
spec:
  type: LoadBalancer
  selector:
    app: fitness-notification-api
  ports:
    - protocol: TCP
      port: 84
      targetPort: 5004
      nodePort: 30004   # Must be between 30000–32767