apiVersion: v1
kind: Service
metadata:
  name: fitness-workout-service
spec:
  type: LoadBalancer
  selector:
    app: fitness-workout-api
  ports:
    - protocol: TCP
      port: 82
      targetPort: 5002
      nodePort: 30002   # Must be between 30000–32767