apiVersion: v1
kind: Service
metadata:
  name: fitness-auth-service
spec:
  type: LoadBalancer
  selector:
    app: fitness-auth-api
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001
      nodePort: 30001   # Must be between 30000–32767