apiVersion: v1
kind: Service
metadata:
  name: fitness-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: fitness-gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000   # Must be between 30000–32767