apiVersion: v1
kind: Service
metadata:
  name: fitness-movegoals-service
spec:
  type: LoadBalancer
  selector:
    app: fitness-movegoals-api
  ports:
    - protocol: TCP
      port: 85
      targetPort: 5005
      nodePort: 30005   # Must be between 30000–32767